### ISSUE TITLE
Yup schema types

### ISSUE THREAD

**Issue by kekoawong** [delphictech/expo-template#39]
### 🌟 **Describe this enhancement:**
___  
Add the typed yup schemas in the utils/schema file.

### ❓ **Why is this enhancement needed or beneficial?**
___  
Will allow us to know the types that should be returned from a form, stricter data recovery.

### 🔗 **Useful Resources:**
___ 

- [Example}(https://github.com/jquense/yup#getting-started)

**Comment by SethY8s** [comment]
Outdated as we move to v2
