### ISSUE TITLE
Update branch names

### ISSUE THREAD

**Issue by SethY8s** [delphictech/expo-template#47]
* change main to v1
* change v2 to the main branch
* make v1 disabled. (protect this branch and disable commits to it)

ChatGtp recommendation:
1. Set v2 as the New Main Branch
Before you deactivate v1, you need to set v2 as your main branch:
Go to your repository on GitHub.
Click on the Settings tab.
In the left sidebar, select Branches.
Under Default branch, click Change default branch.
Select v2 from the dropdown and click Update.
Now, v2 will be your new main branch, and GitHub will treat it as the primary branch for development.
2. Protect the v1 Branch (Make It Read-Only)
Once you've set v2 as the default branch, you can protect the v1 branch and prevent any further pushes or modifications to it. Here's how to do that:
Go to your repository on GitHub.
Click on the Settings tab.
In the left sidebar, select Branches under the Code and automation section.
Scroll down to Branch protection rules and click Add rule.
In the Branch name pattern field, type v1 (or the exact branch name you want to protect).
Enable the following settings:
Protect this branch: This ensures the branch cannot be force-pushed or deleted.
Restrict who can push to matching branches: Enable this to make the branch read-only or limit who can push to it (you can leave it set to "nobody" or only specific admins).
(Optional) Enable Require pull request reviews before merging to ensure any changes that do happen are well-reviewed.
Click Create or Save changes to apply the protection rule.

**Comment by kekoawong** [comment]
Completed with #53
